version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "5000:5000"              # host:container
    environment:
      FLASK_PORT: "5000"
      DB_HOST: db
      DB_USER: secuser
      DB_PASSWORD: "12345678"
      DB_NAME: securedevops
      SHOW_VULN: "1"             # set "0" to hide /vuln_login
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: securedevops
      MYSQL_USER: secuser
      MYSQL_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /home/yogita-jain/mysql-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  db_data:
