apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_DATABASE
          value: "securedevops"
        - name: MYSQL_USER
          value: "secuser"
        - name: MYSQL_PASSWORD
          value: "StrongPass123"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql   # important: mount as a single file
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      - name: mysql-init-script
        configMap:
          name: mysql-init-config
